"""v0.2 search reference data

CLDR 48.2 official languages and names, ISO 3166-2 subdivision names for the five subdivisions the
repo holds, and the starting `country_subdivision_types` rows (ADR-053, ADR-055, ADR-057). Rows are
literals, as `COUNTRIES` is in `c8e1b73f2d04`: regenerating the data never changes a migration
that has already run. The literals are `make reference-data PY=1`.

Ends with the first `refresh_catalog_search` over every catalog, so rows seeded before this
revision are searchable straight away. A later data migration that adds names or languages ends
the same way.

`ON CONFLICT DO NOTHING`, as in `b41f7c9ade52`, so an operator who added a row by hand to unblock
something can still migrate. Subdivision names are only loaded for subdivisions present in
`subdivisions`; a migration that adds a subdivision adds its names too.

The downgrade deletes only what this revision inserted, by value. The tables themselves go with
the previous revision's downgrade.

Revision ID: 2eb49a8f4664
Revises: 847ef861dbdb
Create Date: 2026-10-02

"""

# ruff: noqa: RUF001 - names are real data: typographic apostrophes, dotless i, okina

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2eb49a8f4664"
down_revision: str | None = "847ef861dbdb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

COUNTRY_LANGUAGES = [
    ("AD", "ca"),
    ("AE", "ar"),
    ("AF", "fa"),
    ("AF", "ps"),
    ("AG", "en"),
    ("AI", "en"),
    ("AL", "sq"),
    ("AM", "hy"),
    ("AO", "pt"),
    ("AR", "es"),
    ("AS", "sm"),
    ("AT", "de"),
    ("AU", "en"),
    ("AW", "nl"),
    ("AW", "pap"),
    ("AX", "sv"),
    ("AZ", "az"),
    ("BA", "bs"),
    ("BA", "hr"),
    ("BA", "sr"),
    ("BB", "en"),
    ("BD", "bn"),
    ("BE", "de"),
    ("BE", "fr"),
    ("BE", "nl"),
    ("BF", "fr"),
    ("BG", "bg"),
    ("BH", "ar"),
    ("BI", "en"),
    ("BI", "fr"),
    ("BI", "rn"),
    ("BJ", "fr"),
    ("BL", "fr"),
    ("BM", "en"),
    ("BN", "ms"),
    ("BO", "ay"),
    ("BO", "es"),
    ("BO", "qu"),
    ("BQ", "nl"),
    ("BR", "pt"),
    ("BS", "en"),
    ("BT", "dz"),
    ("BW", "en"),
    ("BW", "tn"),
    ("BY", "be"),
    ("BY", "ru"),
    ("BZ", "en"),
    ("CA", "en"),
    ("CA", "fr"),
    ("CC", "en"),
    ("CD", "fr"),
    ("CF", "fr"),
    ("CF", "sg"),
    ("CG", "fr"),
    ("CH", "de"),
    ("CH", "fr"),
    ("CH", "it"),
    ("CI", "fr"),
    ("CK", "en"),
    ("CL", "es"),
    ("CM", "en"),
    ("CM", "fr"),
    ("CN", "zh"),
    ("CO", "es"),
    ("CR", "es"),
    ("CU", "es"),
    ("CV", "pt"),
    ("CW", "nl"),
    ("CX", "en"),
    ("CY", "el"),
    ("CY", "tr"),
    ("CZ", "cs"),
    ("DE", "de"),
    ("DJ", "ar"),
    ("DJ", "fr"),
    ("DK", "da"),
    ("DM", "en"),
    ("DO", "es"),
    ("DZ", "ar"),
    ("DZ", "fr"),
    ("EC", "es"),
    ("EC", "qu"),
    ("EE", "et"),
    ("EG", "ar"),
    ("EH", "ar"),
    ("ER", "ar"),
    ("ER", "en"),
    ("ES", "es"),
    ("ET", "am"),
    ("FI", "fi"),
    ("FI", "sv"),
    ("FJ", "en"),
    ("FJ", "fj"),
    ("FJ", "hif"),
    ("FK", "en"),
    ("FM", "en"),
    ("FO", "fo"),
    ("FR", "fr"),
    ("GA", "fr"),
    ("GB", "en"),
    ("GD", "en"),
    ("GE", "ka"),
    ("GF", "fr"),
    ("GG", "en"),
    ("GH", "en"),
    ("GI", "en"),
    ("GL", "kl"),
    ("GM", "en"),
    ("GN", "fr"),
    ("GP", "fr"),
    ("GQ", "es"),
    ("GQ", "fr"),
    ("GQ", "pt"),
    ("GR", "el"),
    ("GS", "en"),
    ("GT", "es"),
    ("GU", "ch"),
    ("GW", "pt"),
    ("GY", "en"),
    ("HK", "en"),
    ("HK", "zh"),
    ("HN", "es"),
    ("HR", "hr"),
    ("HT", "fr"),
    ("HT", "ht"),
    ("HU", "hu"),
    ("ID", "id"),
    ("IE", "en"),
    ("IE", "ga"),
    ("IL", "ar"),
    ("IL", "he"),
    ("IM", "en"),
    ("IM", "gv"),
    ("IN", "en"),
    ("IN", "hi"),
    ("IO", "en"),
    ("IQ", "ar"),
    ("IR", "fa"),
    ("IS", "is"),
    ("IT", "it"),
    ("JE", "en"),
    ("JM", "en"),
    ("JO", "ar"),
    ("JP", "ja"),
    ("KE", "en"),
    ("KE", "sw"),
    ("KG", "ky"),
    ("KG", "ru"),
    ("KH", "km"),
    ("KI", "en"),
    ("KI", "gil"),
    ("KM", "ar"),
    ("KM", "fr"),
    ("KM", "wni"),
    ("KM", "zdj"),
    ("KN", "en"),
    ("KP", "ko"),
    ("KR", "ko"),
    ("KW", "ar"),
    ("KY", "en"),
    ("KZ", "kk"),
    ("KZ", "ru"),
    ("LA", "lo"),
    ("LB", "ar"),
    ("LC", "en"),
    ("LI", "de"),
    ("LK", "si"),
    ("LK", "ta"),
    ("LR", "en"),
    ("LS", "en"),
    ("LS", "st"),
    ("LT", "lt"),
    ("LU", "de"),
    ("LU", "fr"),
    ("LU", "lb"),
    ("LV", "lv"),
    ("LY", "ar"),
    ("MA", "ar"),
    ("MA", "tzm"),
    ("MC", "fr"),
    ("MD", "ro"),
    ("ME", "sr"),
    ("MF", "fr"),
    ("MG", "en"),
    ("MG", "fr"),
    ("MG", "mg"),
    ("MH", "en"),
    ("MH", "mh"),
    ("MK", "mk"),
    ("ML", "fr"),
    ("MM", "my"),
    ("MN", "mn"),
    ("MO", "pt"),
    ("MO", "zh"),
    ("MP", "en"),
    ("MQ", "fr"),
    ("MR", "ar"),
    ("MS", "en"),
    ("MT", "en"),
    ("MT", "mt"),
    ("MU", "en"),
    ("MU", "fr"),
    ("MV", "dv"),
    ("MW", "en"),
    ("MW", "ny"),
    ("MX", "es"),
    ("MY", "ms"),
    ("MZ", "pt"),
    ("NA", "en"),
    ("NC", "fr"),
    ("NE", "fr"),
    ("NF", "en"),
    ("NG", "en"),
    ("NG", "yo"),
    ("NI", "es"),
    ("NL", "nl"),
    ("NO", "nb"),
    ("NO", "nn"),
    ("NO", "no"),
    ("NP", "ne"),
    ("NR", "en"),
    ("NR", "na"),
    ("NU", "en"),
    ("NU", "niu"),
    ("NZ", "mi"),
    ("OM", "ar"),
    ("PA", "es"),
    ("PE", "es"),
    ("PE", "qu"),
    ("PF", "fr"),
    ("PF", "ty"),
    ("PG", "en"),
    ("PG", "ho"),
    ("PG", "tpi"),
    ("PH", "en"),
    ("PH", "fil"),
    ("PK", "en"),
    ("PK", "ur"),
    ("PL", "pl"),
    ("PM", "fr"),
    ("PN", "en"),
    ("PR", "es"),
    ("PS", "ar"),
    ("PT", "pt"),
    ("PW", "en"),
    ("PW", "pau"),
    ("PY", "es"),
    ("PY", "gn"),
    ("QA", "ar"),
    ("RE", "fr"),
    ("RO", "ro"),
    ("RS", "sr"),
    ("RU", "ru"),
    ("RW", "en"),
    ("RW", "fr"),
    ("RW", "rw"),
    ("SA", "ar"),
    ("SB", "en"),
    ("SC", "en"),
    ("SC", "fr"),
    ("SD", "ar"),
    ("SD", "en"),
    ("SE", "sv"),
    ("SG", "en"),
    ("SG", "ms"),
    ("SG", "ta"),
    ("SG", "zh"),
    ("SH", "en"),
    ("SI", "sl"),
    ("SJ", "nb"),
    ("SK", "sk"),
    ("SL", "en"),
    ("SM", "it"),
    ("SN", "fr"),
    ("SO", "ar"),
    ("SO", "so"),
    ("SR", "nl"),
    ("SS", "en"),
    ("ST", "pt"),
    ("SV", "es"),
    ("SX", "en"),
    ("SX", "nl"),
    ("SY", "ar"),
    ("SZ", "en"),
    ("SZ", "ss"),
    ("TC", "en"),
    ("TD", "ar"),
    ("TD", "fr"),
    ("TG", "fr"),
    ("TH", "th"),
    ("TJ", "tg"),
    ("TK", "en"),
    ("TK", "tkl"),
    ("TL", "pt"),
    ("TL", "tet"),
    ("TM", "tk"),
    ("TN", "ar"),
    ("TN", "fr"),
    ("TO", "en"),
    ("TO", "to"),
    ("TR", "tr"),
    ("TT", "en"),
    ("TV", "en"),
    ("TV", "tvl"),
    ("TW", "hak"),
    ("TW", "nan"),
    ("TW", "zh"),
    ("TZ", "en"),
    ("TZ", "sw"),
    ("UA", "uk"),
    ("UG", "en"),
    ("UG", "sw"),
    ("UM", "en"),
    ("US", "en"),
    ("UY", "es"),
    ("UZ", "uz"),
    ("VA", "it"),
    ("VC", "en"),
    ("VE", "es"),
    ("VG", "en"),
    ("VI", "en"),
    ("VN", "vi"),
    ("VU", "bi"),
    ("VU", "en"),
    ("VU", "fr"),
    ("WF", "fr"),
    ("WS", "en"),
    ("WS", "sm"),
    ("YE", "ar"),
    ("YT", "fr"),
    ("ZA", "en"),
    ("ZM", "en"),
    ("ZW", "en"),
    ("ZW", "nd"),
    ("ZW", "sn"),
]
COUNTRY_NAMES = [
    ("AD", "ca", "Andorra"),
    ("AD", "en", "Andorra"),
    ("AE", "ar", "الإمارات العربية المتحدة"),
    ("AE", "en", "United Arab Emirates"),
    ("AF", "en", "Afghanistan"),
    ("AF", "fa", "افغانستان"),
    ("AF", "ps", "افغانستان"),
    ("AG", "en", "Antigua & Barbuda"),
    ("AI", "en", "Anguilla"),
    ("AL", "en", "Albania"),
    ("AL", "sq", "Shqipëri"),
    ("AM", "en", "Armenia"),
    ("AM", "hy", "Հայաստան"),
    ("AO", "en", "Angola"),
    ("AO", "pt", "Angola"),
    ("AQ", "en", "Antarctica"),
    ("AR", "en", "Argentina"),
    ("AR", "es", "Argentina"),
    ("AS", "en", "American Samoa"),
    ("AT", "de", "Österreich"),
    ("AT", "en", "Austria"),
    ("AU", "en", "Australia"),
    ("AW", "en", "Aruba"),
    ("AW", "nl", "Aruba"),
    ("AX", "en", "Åland Islands"),
    ("AX", "sv", "Åland"),
    ("AZ", "az", "Azərbaycan"),
    ("AZ", "en", "Azerbaijan"),
    ("BA", "bs", "Bosna i Hercegovina"),
    ("BA", "en", "Bosnia"),
    ("BA", "en", "Bosnia & Herzegovina"),
    ("BA", "hr", "Bosna i Hercegovina"),
    ("BA", "sr", "Босна и Херцеговина"),
    ("BB", "en", "Barbados"),
    ("BD", "bn", "বাংলাদেশ"),
    ("BD", "en", "Bangladesh"),
    ("BE", "de", "Belgien"),
    ("BE", "en", "Belgium"),
    ("BE", "fr", "Belgique"),
    ("BE", "nl", "België"),
    ("BF", "en", "Burkina Faso"),
    ("BF", "fr", "Burkina Faso"),
    ("BG", "bg", "България"),
    ("BG", "en", "Bulgaria"),
    ("BH", "ar", "البحرين"),
    ("BH", "en", "Bahrain"),
    ("BI", "en", "Burundi"),
    ("BI", "fr", "Burundi"),
    ("BI", "rn", "Uburundi"),
    ("BJ", "en", "Benin"),
    ("BJ", "fr", "Bénin"),
    ("BL", "en", "St. Barthélemy"),
    ("BL", "fr", "Saint-Barthélemy"),
    ("BM", "en", "Bermuda"),
    ("BN", "en", "Brunei"),
    ("BN", "ms", "Brunei"),
    ("BO", "en", "Bolivia"),
    ("BO", "es", "Bolivia"),
    ("BO", "qu", "Bolivia"),
    ("BQ", "en", "Caribbean Netherlands"),
    ("BQ", "nl", "Caribisch Nederland"),
    ("BR", "en", "Brazil"),
    ("BR", "pt", "Brasil"),
    ("BS", "en", "Bahamas"),
    ("BT", "dz", "འབྲུག"),
    ("BT", "en", "Bhutan"),
    ("BV", "en", "Bouvet Island"),
    ("BW", "en", "Botswana"),
    ("BW", "tn", "Botswana"),
    ("BY", "be", "Беларусь"),
    ("BY", "en", "Belarus"),
    ("BY", "ru", "Беларусь"),
    ("BZ", "en", "Belize"),
    ("CA", "en", "Canada"),
    ("CA", "fr", "Canada"),
    ("CC", "en", "Cocos (Keeling) Islands"),
    ("CC", "en", "Cocos Islands"),
    ("CD", "en", "Congo (DRC)"),
    ("CD", "en", "Congo - Kinshasa"),
    ("CD", "fr", "Congo (RDC)"),
    ("CD", "fr", "Congo-Kinshasa"),
    ("CF", "en", "Central African Republic"),
    ("CF", "fr", "République centrafricaine"),
    ("CF", "sg", "Ködörösêse tî Bêafrîka"),
    ("CG", "en", "Congo (Republic)"),
    ("CG", "en", "Congo - Brazzaville"),
    ("CG", "fr", "Congo-Brazzaville"),
    ("CG", "fr", "République du Congo"),
    ("CH", "de", "Schweiz"),
    ("CH", "en", "Switzerland"),
    ("CH", "fr", "Suisse"),
    ("CH", "it", "Svizzera"),
    ("CI", "en", "Côte d’Ivoire"),
    ("CI", "en", "Ivory Coast"),
    ("CI", "fr", "Côte d’Ivoire"),
    ("CI", "fr", "République de Côte d’Ivoire"),
    ("CK", "en", "Cook Islands"),
    ("CL", "en", "Chile"),
    ("CL", "es", "Chile"),
    ("CM", "en", "Cameroon"),
    ("CM", "fr", "Cameroun"),
    ("CN", "en", "China"),
    ("CN", "zh", "中国"),
    ("CO", "en", "Colombia"),
    ("CO", "es", "Colombia"),
    ("CR", "en", "Costa Rica"),
    ("CR", "es", "Costa Rica"),
    ("CU", "en", "Cuba"),
    ("CU", "es", "Cuba"),
    ("CV", "en", "Cabo Verde"),
    ("CV", "en", "Cape Verde"),
    ("CV", "pt", "Cabo Verde"),
    ("CW", "en", "Curaçao"),
    ("CW", "nl", "Curaçao"),
    ("CX", "en", "Christmas Island"),
    ("CY", "el", "Κύπρος"),
    ("CY", "en", "Cyprus"),
    ("CY", "tr", "Kıbrıs"),
    ("CZ", "cs", "Česko"),
    ("CZ", "cs", "Česká republika"),
    ("CZ", "en", "Czech Republic"),
    ("CZ", "en", "Czechia"),
    ("DE", "de", "Deutschland"),
    ("DE", "en", "Germany"),
    ("DJ", "ar", "جيبوتي"),
    ("DJ", "en", "Djibouti"),
    ("DJ", "fr", "Djibouti"),
    ("DK", "da", "Danmark"),
    ("DK", "en", "Denmark"),
    ("DM", "en", "Dominica"),
    ("DO", "en", "Dominican Republic"),
    ("DO", "es", "República Dominicana"),
    ("DZ", "ar", "الجزائر"),
    ("DZ", "en", "Algeria"),
    ("DZ", "fr", "Algérie"),
    ("EC", "en", "Ecuador"),
    ("EC", "es", "Ecuador"),
    ("EC", "qu", "Ecuador"),
    ("EE", "en", "Estonia"),
    ("EE", "et", "Eesti"),
    ("EG", "ar", "مصر"),
    ("EG", "en", "Egypt"),
    ("EH", "ar", "الصحراء الغربية"),
    ("EH", "en", "Western Sahara"),
    ("ER", "ar", "إريتريا"),
    ("ER", "en", "Eritrea"),
    ("ES", "en", "Spain"),
    ("ES", "es", "España"),
    ("ET", "am", "ኢትዮጵያ"),
    ("ET", "en", "Ethiopia"),
    ("FI", "en", "Finland"),
    ("FI", "fi", "Suomi"),
    ("FI", "sv", "Finland"),
    ("FJ", "en", "Fiji"),
    ("FK", "en", "Falkland Islands"),
    ("FK", "en", "Falkland Islands (Islas Malvinas)"),
    ("FM", "en", "Micronesia"),
    ("FO", "en", "Faroe Islands"),
    ("FO", "fo", "Føroyar"),
    ("FR", "en", "France"),
    ("FR", "fr", "France"),
    ("GA", "en", "Gabon"),
    ("GA", "fr", "Gabon"),
    ("GB", "en", "UK"),
    ("GB", "en", "United Kingdom"),
    ("GD", "en", "Grenada"),
    ("GE", "en", "Georgia"),
    ("GE", "ka", "საქართველო"),
    ("GF", "en", "French Guiana"),
    ("GF", "fr", "Guyane française"),
    ("GG", "en", "Guernsey"),
    ("GH", "en", "Ghana"),
    ("GI", "en", "Gibraltar"),
    ("GL", "en", "Greenland"),
    ("GL", "kl", "Kalaallit Nunaat"),
    ("GM", "en", "Gambia"),
    ("GN", "en", "Guinea"),
    ("GN", "fr", "Guinée"),
    ("GP", "en", "Guadeloupe"),
    ("GP", "fr", "Guadeloupe"),
    ("GQ", "en", "Equatorial Guinea"),
    ("GQ", "es", "Guinea Ecuatorial"),
    ("GQ", "fr", "Guinée équatoriale"),
    ("GQ", "pt", "Guiné Equatorial"),
    ("GR", "el", "Ελλάδα"),
    ("GR", "en", "Greece"),
    ("GS", "en", "South Georgia & South Sandwich Islands"),
    ("GT", "en", "Guatemala"),
    ("GT", "es", "Guatemala"),
    ("GU", "en", "Guam"),
    ("GW", "en", "Guinea-Bissau"),
    ("GW", "pt", "Guiné-Bissau"),
    ("GY", "en", "Guyana"),
    ("HK", "en", "Hong Kong"),
    ("HK", "en", "Hong Kong SAR China"),
    ("HK", "zh", "中国香港特别行政区"),
    ("HK", "zh", "香港"),
    ("HM", "en", "Heard & McDonald Islands"),
    ("HN", "en", "Honduras"),
    ("HN", "es", "Honduras"),
    ("HR", "en", "Croatia"),
    ("HR", "hr", "Hrvatska"),
    ("HT", "en", "Haiti"),
    ("HT", "fr", "Haïti"),
    ("HT", "ht", "Haïti"),
    ("HU", "en", "Hungary"),
    ("HU", "hu", "Magyarország"),
    ("ID", "en", "Indonesia"),
    ("ID", "id", "Indonesia"),
    ("IE", "en", "Ireland"),
    ("IE", "ga", "Éire"),
    ("IL", "ar", "إسرائيل"),
    ("IL", "en", "Israel"),
    ("IL", "he", "ישראל"),
    ("IM", "en", "Isle of Man"),
    ("IM", "gv", "Ellan Vannin"),
    ("IN", "en", "India"),
    ("IN", "hi", "भारत"),
    ("IO", "en", "British Indian Ocean Territory"),
    ("IQ", "ar", "العراق"),
    ("IQ", "en", "Iraq"),
    ("IR", "en", "Iran"),
    ("IR", "fa", "ایران"),
    ("IS", "en", "Iceland"),
    ("IS", "is", "Ísland"),
    ("IT", "en", "Italy"),
    ("IT", "it", "Italia"),
    ("JE", "en", "Jersey"),
    ("JM", "en", "Jamaica"),
    ("JO", "ar", "الأردن"),
    ("JO", "en", "Jordan"),
    ("JP", "en", "Japan"),
    ("JP", "ja", "日本"),
    ("KE", "en", "Kenya"),
    ("KE", "sw", "Kenya"),
    ("KG", "en", "Kyrgyzstan"),
    ("KG", "ky", "Кыргызстан"),
    ("KG", "ru", "Киргизия"),
    ("KH", "en", "Cambodia"),
    ("KH", "km", "កម្ពុជា"),
    ("KI", "en", "Kiribati"),
    ("KM", "ar", "جزر القمر"),
    ("KM", "en", "Comoros"),
    ("KM", "fr", "Comores"),
    ("KN", "en", "St. Kitts & Nevis"),
    ("KP", "en", "North Korea"),
    ("KP", "ko", "북한"),
    ("KR", "en", "South Korea"),
    ("KR", "ko", "대한민국"),
    ("KR", "ko", "한국"),
    ("KW", "ar", "الكويت"),
    ("KW", "en", "Kuwait"),
    ("KY", "en", "Cayman Islands"),
    ("KZ", "en", "Kazakhstan"),
    ("KZ", "kk", "Қазақстан"),
    ("KZ", "ru", "Казахстан"),
    ("LA", "en", "Laos"),
    ("LA", "lo", "ລາວ"),
    ("LB", "ar", "لبنان"),
    ("LB", "en", "Lebanon"),
    ("LC", "en", "St. Lucia"),
    ("LI", "de", "Liechtenstein"),
    ("LI", "en", "Liechtenstein"),
    ("LK", "en", "Sri Lanka"),
    ("LK", "si", "ශ්\u200dරී ලංකාව"),
    ("LK", "ta", "இலங்கை"),
    ("LR", "en", "Liberia"),
    ("LS", "en", "Lesotho"),
    ("LS", "st", "Lesotho"),
    ("LT", "en", "Lithuania"),
    ("LT", "lt", "Lietuva"),
    ("LU", "de", "Luxemburg"),
    ("LU", "en", "Luxembourg"),
    ("LU", "fr", "Luxembourg"),
    ("LU", "lb", "Lëtzebuerg"),
    ("LV", "en", "Latvia"),
    ("LV", "lv", "Latvija"),
    ("LY", "ar", "ليبيا"),
    ("LY", "en", "Libya"),
    ("MA", "ar", "المغرب"),
    ("MA", "en", "Morocco"),
    ("MA", "tzm", "Meṛṛuk"),
    ("MC", "en", "Monaco"),
    ("MC", "fr", "Monaco"),
    ("MD", "en", "Moldova"),
    ("MD", "ro", "Republica Moldova"),
    ("ME", "en", "Montenegro"),
    ("ME", "sr", "Црна Гора"),
    ("MF", "en", "St. Martin"),
    ("MF", "fr", "Saint-Martin"),
    ("MG", "en", "Madagascar"),
    ("MG", "fr", "Madagascar"),
    ("MG", "mg", "Madagasikara"),
    ("MH", "en", "Marshall Islands"),
    ("MK", "en", "North Macedonia"),
    ("MK", "mk", "Северна Македонија"),
    ("ML", "en", "Mali"),
    ("ML", "fr", "Mali"),
    ("MM", "en", "Myanmar"),
    ("MM", "en", "Myanmar (Burma)"),
    ("MM", "my", "မြန်မာ"),
    ("MN", "en", "Mongolia"),
    ("MN", "mn", "Монгол"),
    ("MO", "en", "Macao"),
    ("MO", "en", "Macao SAR China"),
    ("MO", "pt", "Macau"),
    ("MO", "pt", "Macau, RAE da China"),
    ("MO", "zh", "中国澳门特别行政区"),
    ("MO", "zh", "澳门"),
    ("MP", "en", "Northern Mariana Islands"),
    ("MQ", "en", "Martinique"),
    ("MQ", "fr", "Martinique"),
    ("MR", "ar", "موريتانيا"),
    ("MR", "en", "Mauritania"),
    ("MS", "en", "Montserrat"),
    ("MT", "en", "Malta"),
    ("MT", "mt", "Malta"),
    ("MU", "en", "Mauritius"),
    ("MU", "fr", "Maurice"),
    ("MV", "en", "Maldives"),
    ("MW", "en", "Malawi"),
    ("MX", "en", "Mexico"),
    ("MX", "es", "México"),
    ("MY", "en", "Malaysia"),
    ("MY", "ms", "Malaysia"),
    ("MZ", "en", "Mozambique"),
    ("MZ", "pt", "Moçambique"),
    ("NA", "en", "Namibia"),
    ("NC", "en", "New Caledonia"),
    ("NC", "fr", "Nouvelle-Calédonie"),
    ("NE", "en", "Niger"),
    ("NE", "fr", "Niger"),
    ("NF", "en", "Norfolk Island"),
    ("NG", "en", "Nigeria"),
    ("NG", "yo", "Nàìjíríà"),
    ("NI", "en", "Nicaragua"),
    ("NI", "es", "Nicaragua"),
    ("NL", "en", "Netherlands"),
    ("NL", "nl", "Nederland"),
    ("NO", "en", "Norway"),
    ("NO", "nb", "Norge"),
    ("NO", "nn", "Noreg"),
    ("NO", "no", "Norge"),
    ("NP", "en", "Nepal"),
    ("NP", "ne", "नेपाल"),
    ("NR", "en", "Nauru"),
    ("NU", "en", "Niue"),
    ("NZ", "en", "Aotearoa New Zealand"),
    ("NZ", "en", "New Zealand"),
    ("NZ", "mi", "Aotearoa"),
    ("OM", "ar", "عُمان"),
    ("OM", "en", "Oman"),
    ("PA", "en", "Panama"),
    ("PA", "es", "Panamá"),
    ("PE", "en", "Peru"),
    ("PE", "es", "Perú"),
    ("PE", "qu", "Perú"),
    ("PF", "en", "French Polynesia"),
    ("PF", "fr", "Polynésie française"),
    ("PG", "en", "Papua New Guinea"),
    ("PG", "tpi", "Papua Niugini"),
    ("PH", "en", "Philippines"),
    ("PH", "fil", "Pilipinas"),
    ("PK", "en", "Pakistan"),
    ("PK", "ur", "پاکستان"),
    ("PL", "en", "Poland"),
    ("PL", "pl", "Polska"),
    ("PM", "en", "St. Pierre & Miquelon"),
    ("PM", "fr", "Saint-Pierre-et-Miquelon"),
    ("PN", "en", "Pitcairn"),
    ("PN", "en", "Pitcairn Islands"),
    ("PR", "en", "Puerto Rico"),
    ("PR", "es", "Puerto Rico"),
    ("PS", "ar", "الأراضي الفلسطينية"),
    ("PS", "ar", "فلسطين"),
    ("PS", "en", "Palestine"),
    ("PS", "en", "Palestinian Territories"),
    ("PT", "en", "Portugal"),
    ("PT", "pt", "Portugal"),
    ("PW", "en", "Palau"),
    ("PY", "en", "Paraguay"),
    ("PY", "es", "Paraguay"),
    ("QA", "ar", "قطر"),
    ("QA", "en", "Qatar"),
    ("RE", "en", "Réunion"),
    ("RE", "fr", "La Réunion"),
    ("RO", "en", "Romania"),
    ("RO", "ro", "România"),
    ("RS", "en", "Serbia"),
    ("RS", "sr", "Србија"),
    ("RU", "en", "Russia"),
    ("RU", "ru", "Россия"),
    ("RW", "en", "Rwanda"),
    ("RW", "fr", "Rwanda"),
    ("RW", "rw", "U Rwanda"),
    ("SA", "ar", "المملكة العربية السعودية"),
    ("SA", "en", "Saudi Arabia"),
    ("SB", "en", "Solomon Islands"),
    ("SC", "en", "Seychelles"),
    ("SC", "fr", "Seychelles"),
    ("SD", "ar", "السودان"),
    ("SD", "en", "Sudan"),
    ("SE", "en", "Sweden"),
    ("SE", "sv", "Sverige"),
    ("SG", "en", "Singapore"),
    ("SG", "ms", "Singapura"),
    ("SG", "ta", "சிங்கப்பூர்"),
    ("SG", "zh", "新加坡"),
    ("SH", "en", "St. Helena"),
    ("SI", "en", "Slovenia"),
    ("SI", "sl", "Slovenija"),
    ("SJ", "en", "Svalbard & Jan Mayen"),
    ("SJ", "nb", "Svalbard og Jan Mayen"),
    ("SK", "en", "Slovakia"),
    ("SK", "sk", "Slovensko"),
    ("SL", "en", "Sierra Leone"),
    ("SM", "en", "San Marino"),
    ("SM", "it", "San Marino"),
    ("SN", "en", "Senegal"),
    ("SN", "fr", "Sénégal"),
    ("SO", "ar", "الصومال"),
    ("SO", "en", "Somalia"),
    ("SO", "so", "Soomaaliya"),
    ("SR", "en", "Suriname"),
    ("SR", "nl", "Suriname"),
    ("SS", "en", "South Sudan"),
    ("ST", "en", "São Tomé & Príncipe"),
    ("ST", "pt", "São Tomé e Príncipe"),
    ("SV", "en", "El Salvador"),
    ("SV", "es", "El Salvador"),
    ("SX", "en", "Sint Maarten"),
    ("SX", "nl", "Sint-Maarten"),
    ("SY", "ar", "سوريا"),
    ("SY", "en", "Syria"),
    ("SZ", "en", "Eswatini"),
    ("SZ", "en", "Swaziland"),
    ("SZ", "ss", "eSwatini"),
    ("TC", "en", "Turks & Caicos Islands"),
    ("TD", "ar", "تشاد"),
    ("TD", "en", "Chad"),
    ("TD", "fr", "Tchad"),
    ("TF", "en", "French Southern Territories"),
    ("TG", "en", "Togo"),
    ("TG", "fr", "Togo"),
    ("TH", "en", "Thailand"),
    ("TH", "th", "ไทย"),
    ("TJ", "en", "Tajikistan"),
    ("TJ", "tg", "Тоҷикистон"),
    ("TK", "en", "Tokelau"),
    ("TL", "en", "East Timor"),
    ("TL", "en", "Timor-Leste"),
    ("TL", "pt", "República Democrática de Timor-Leste"),
    ("TL", "pt", "Timor-Leste"),
    ("TM", "en", "Turkmenistan"),
    ("TM", "tk", "Türkmenistan"),
    ("TN", "ar", "تونس"),
    ("TN", "en", "Tunisia"),
    ("TN", "fr", "Tunisie"),
    ("TO", "en", "Tonga"),
    ("TO", "to", "Tonga"),
    ("TR", "en", "Turkey"),
    ("TR", "en", "Türkiye"),
    ("TR", "tr", "Türkiye"),
    ("TT", "en", "Trinidad & Tobago"),
    ("TV", "en", "Tuvalu"),
    ("TW", "en", "Taiwan"),
    ("TW", "zh", "台湾"),
    ("TZ", "en", "Tanzania"),
    ("TZ", "sw", "Tanzania"),
    ("UA", "en", "Ukraine"),
    ("UA", "uk", "Україна"),
    ("UG", "en", "Uganda"),
    ("UG", "sw", "Uganda"),
    ("UM", "en", "U.S. Outlying Islands"),
    ("US", "en", "US"),
    ("US", "en", "United States"),
    ("UY", "en", "Uruguay"),
    ("UY", "es", "Uruguay"),
    ("UZ", "en", "Uzbekistan"),
    ("UZ", "uz", "Oʻzbekiston"),
    ("VA", "en", "Vatican City"),
    ("VA", "it", "Città del Vaticano"),
    ("VC", "en", "St. Vincent & Grenadines"),
    ("VE", "en", "Venezuela"),
    ("VE", "es", "Venezuela"),
    ("VG", "en", "British Virgin Islands"),
    ("VI", "en", "U.S. Virgin Islands"),
    ("VN", "en", "Vietnam"),
    ("VN", "vi", "Việt Nam"),
    ("VU", "en", "Vanuatu"),
    ("VU", "fr", "Vanuatu"),
    ("WF", "en", "Wallis & Futuna"),
    ("WF", "fr", "Wallis-et-Futuna"),
    ("WS", "en", "Samoa"),
    ("YE", "ar", "اليمن"),
    ("YE", "en", "Yemen"),
    ("YT", "en", "Mayotte"),
    ("YT", "fr", "Mayotte"),
    ("ZA", "en", "South Africa"),
    ("ZM", "en", "Zambia"),
    ("ZW", "en", "Zimbabwe"),
    ("ZW", "nd", "Zimbabwe"),
    ("ZW", "sn", "Zimbabwe"),
]
SUBDIVISION_NAMES = [
    ("BE-BRU", "de", "Brüssel"),
    ("BE-BRU", "en", "Brussels"),
    ("BE-BRU", "fr", "Région de Bruxelles-Capitale"),
    ("BE-BRU", "nl", "Brussels Hoofdstedelijk Gewest"),
    ("BE-VLG", "de", "Flandern"),
    ("BE-VLG", "en", "Flanders"),
    ("BE-VLG", "fr", "Flandre"),
    ("BE-VLG", "fr", "Région flamande"),
    ("BE-VLG", "nl", "Vlaams Gewest"),
    ("BE-VLG", "nl", "Vlaanderen"),
    ("BE-WAL", "de", "Wallonien"),
    ("BE-WAL", "en", "Wallonia"),
    ("BE-WAL", "fr", "Wallonie"),
    ("BE-WAL", "nl", "Wallonië"),
    ("CH-VS", "de", "Wallis"),
    ("CH-VS", "en", "Valais"),
    ("CH-VS", "fr", "canton du Valais"),
    ("CH-VS", "it", "Canton Vallese"),
    ("FR-IDF", "en", "Île-de-France"),
    ("FR-IDF", "fr", "Île-de-France"),
]

#: ADR-055, lowercase to match `subdivisions.subdivision_type`. Search does not read this table.
SUBDIVISION_TYPES = [
    ("BE", "region"),
    ("BE", "province"),
    ("CH", "canton"),
    ("CA", "province"),
    ("CA", "territory"),
    ("FR", "metropolitan region"),
    ("FR", "metropolitan department"),
    ("FR", "metropolitan collectivity with special status"),
    ("FR", "overseas departmental collectivity"),
    ("FR", "overseas collectivity"),
    ("FR", "overseas collectivity with special status"),
    ("FR", "overseas unique territorial collectivity"),
]

#: (table, columns, rows). Parents first on the way up; the same order, reversed, on the way down.
TABLES = [
    ("country_languages", ("country_code", "language_tag"), COUNTRY_LANGUAGES),
    ("country_names", ("country_code", "language_tag", "name"), COUNTRY_NAMES),
    ("subdivision_names", ("subdivision_code", "language_tag", "name"), SUBDIVISION_NAMES),
    ("country_subdivision_types", ("country_code", "subdivision_type"), SUBDIVISION_TYPES),
]


def upgrade() -> None:
    bind = op.get_bind()
    for table, columns, rows in TABLES:
        statement = sa.text(
            f"INSERT INTO {table} ({', '.join(columns)}) "
            f"VALUES ({', '.join(':' + c for c in columns)}) ON CONFLICT DO NOTHING"
        )
        bind.execute(statement, [dict(zip(columns, row, strict=True)) for row in rows])
    op.execute("SELECT public.refresh_catalog_search(array_agg(id)) FROM catalogs")


def downgrade() -> None:
    """Remove exactly the rows `upgrade()` inserts, then rebuild the search rows without them.

    A name an operator added by hand has a different value and is left alone. A row inserted by
    hand with the same value is indistinguishable from ours and goes too; these are reference
    values, so that is accepted rather than adding provenance to four lookup tables.
    """
    bind = op.get_bind()
    for table, columns, rows in reversed(TABLES):
        statement = sa.text(
            f"DELETE FROM {table} WHERE " + " AND ".join(f"{c} = :{c}" for c in columns)
        )
        bind.execute(statement, [dict(zip(columns, row, strict=True)) for row in rows])
    op.execute("SELECT public.refresh_catalog_search(array_agg(id)) FROM catalogs")
