"""Vocabularies shared by the database, the wire contract, and validation.

Generated by `scripts/generate_enums.py` from `schema/catalog.schema.json`. Do not edit by
hand. Regenerate with `make enums`.

`LinkRel` and `CatalogStatus` are transcribed rather than derived: neither appears in the
JSON Schema. See the generator for why.
"""

from enum import StrEnum


class CatalogKind(StrEnum):
    OPEN = "open"
    PUBLIC = "public"
    ACADEMIC = "academic"
    SCHOOL = "school"
    SPECIALIZED = "specialized"


class CatalogColor(StrEnum):
    GRAY = "gray"
    RED = "red"
    YELLOW = "yellow"
    BLUE = "blue"
    GREEN = "green"
    PURPLE = "purple"
    ORANGE = "orange"
    PINK = "pink"


class PublicationType(StrEnum):
    EBOOK = "ebook"
    AUDIOBOOK = "audiobook"
    COMIC = "comic"
    NEWSPAPER = "newspaper"
    MAGAZINE = "magazine"
    JOURNAL = "journal"
    ARTICLE = "article"


class CoverageScope(StrEnum):
    GLOBAL = "global"
    COUNTRY = "country"
    SUBDIVISIONS = "subdivisions"
    LOCAL = "local"


class LinkRel(StrEnum):
    SELF = "self"
    CATALOG = "catalog"
    SHELF = "shelf"
    ICON = "icon"
    AUTHENTICATE = "authenticate"
    ALTERNATE = "alternate"
    PROFILE = "profile"
    SEARCH = "search"


class CatalogStatus(StrEnum):
    SUGGESTED = "suggested"
    ACTIVE = "active"
