"""Generate `registry.domain.enums` from `schema/catalog.schema.json`.

Hadrien authors the schema and it changes independently of the service. Hand-copying his
enum values into Python is exactly the duplication that drifts silently, so the file is
generated and committed; CI regenerates and diffs, which turns a schema change into a
failing build with a readable diff instead of a runtime mismatch weeks later.

`link_rel` is **not** in the JSON Schema — it comes from the Notion links table — so it is
transcribed by hand below rather than derived. Being explicit about which enums are derived
and which are transcribed matters when one of them drifts.
"""

import sys
from pathlib import Path

from registry.core.schema_validation import SCHEMA_DIR, load_schema_document

TARGET = Path(__file__).resolve().parents[1] / "src" / "registry" / "domain" / "enums.py"

#: JSON Schema location → the StrEnum to emit for it.
DERIVED = {
    "CatalogKind": ("metadata", "kind"),
    "CatalogColor": ("metadata", "color"),
    "PublicationType": ("metadata", "publicationTypes"),
    "CoverageScope": ("metadata", "coverage"),
}

#: Not in the JSON Schema. ADR-013 — a link carries a single rel, not an array.
LINK_RELS = (
    "self",
    "catalog",
    "shelf",
    "icon",
    "authenticate",
    "alternate",
    "profile",
    "search",
)

#: ADR-010 — internal registry state, so it is not in the catalog contract either.
CATALOG_STATUSES = ("suggested", "active")

HEADER = '''"""Vocabularies shared by the database, the wire contract, and validation.

Generated by `scripts/generate_enums.py` from `schema/catalog.schema.json` — do not edit by
hand. Regenerate with `make enums`.

`LinkRel` and `CatalogStatus` are transcribed rather than derived: neither appears in the
JSON Schema. See the generator for why.
"""

from enum import StrEnum
'''


def extract_values(document: dict, path: tuple[str, ...]) -> list[str]:
    """Read an ``enum`` list from the schema, whether the node is a scalar or an array."""
    node = document["properties"]
    for key in path[:-1]:
        node = node[key]["properties"]
    node = node[path[-1]]
    if node.get("type") == "array":
        node = node["items"]
    return list(node["enum"])


def render_enum(name: str, values: list[str]) -> str:
    members = "\n".join(f'    {value.upper()} = "{value}"' for value in values)
    return f"\n\nclass {name}(StrEnum):\n{members}\n"


def render_module() -> str:
    document = load_schema_document(SCHEMA_DIR / "catalog.schema.json")
    parts = [HEADER]
    for name, path in DERIVED.items():
        parts.append(render_enum(name, extract_values(document, path)))
    parts.append(render_enum("LinkRel", list(LINK_RELS)))
    parts.append(render_enum("CatalogStatus", list(CATALOG_STATUSES)))
    return "".join(parts)


def main() -> int:
    content = render_module()
    if TARGET.exists() and TARGET.read_text(encoding="utf-8") == content:
        print(f"ok   {TARGET.name} is up to date")
        return 0
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
