"""Derive the relaxed seed-input schema from the published feed and catalog schemas.

`data/recommended.json` is an *input* document that happens to resemble the output
document. It has no feed-level `links` and no `self` link on any catalog, both required by
the published schemas, because a `self` link points at a registry that does not exist at
authoring time. The service synthesises those at render time, and the contract tests validate
the output, which is where it matters.

The relaxed variant is **derived, not hand-written**, so it cannot drift from the published
schema when Hadrien edits it. Three relaxations, and nothing else:

1. feed-level `links` is not required
2. the feed's "must contain a `self` link" constraint is dropped
3. the same `self` constraint is dropped from every catalog

Everything else the published schemas assert. Enums, the BCP-47 pattern, `minItems` on
`kind`, `additionalProperties: false` on `metadata`, still applies.
"""

import json
import sys
from typing import Any

from registry.core.schema_validation import SCHEMA_DIR, load_schema_document

TARGET = SCHEMA_DIR / "generated" / "seed-input.schema.json"

BANNER = (
    "GENERATED by scripts/generate_seed_schema.py from feed.schema.json and "
    "catalog.schema.json. Do not edit by hand. Regenerate with `make seed-schema`. "
    "It is derived, never hand-written."
)


def relax_catalog(catalog_schema: dict[str, Any]) -> dict[str, Any]:
    """Drop the `self` requirement from a catalog document."""
    relaxed = json.loads(json.dumps(catalog_schema))
    relaxed.pop("$id", None)
    relaxed["properties"]["links"].pop("contains", None)
    return relaxed


def build_seed_schema() -> dict[str, Any]:
    feed = load_schema_document(SCHEMA_DIR / "feed.schema.json")
    catalog = load_schema_document(SCHEMA_DIR / "catalog.schema.json")

    seed = json.loads(json.dumps(feed))
    seed["$id"] = (
        "https://edrlab.github.io/catalog-registry/schema/generated/seed-input.schema.json"
    )
    seed["title"] = "Catalog Registry Seed Input"
    seed["description"] = BANNER

    seed["required"] = [name for name in seed.get("required", []) if name != "links"]
    seed["properties"]["links"].pop("contains", None)
    # Inline the catalog schema rather than $ref it: the relaxation applies to this copy only,
    # and the published catalog.schema.json must keep requiring `self`.
    seed["properties"]["catalogs"]["items"] = relax_catalog(catalog)
    return seed


def main() -> int:
    content = json.dumps(build_seed_schema(), indent=2, ensure_ascii=False) + "\n"
    if TARGET.exists() and TARGET.read_text(encoding="utf-8") == content:
        print(f"ok   {TARGET.name} is up to date")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(SCHEMA_DIR.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
