"""Regenerate `.env.example` from `Settings`.

Hand-maintaining a second list of environment variables is how it drifts from the first.
`Settings` already knows every key, its default, and what it is for, so the file is rendered
from the model and committed. `tests/unit/test_env_example.py` fails if the committed copy
is stale, which is the same check CI runs.
"""

import sys
from pathlib import Path

from pydantic.fields import FieldInfo

from registry.core.config import Settings

REPO_ROOT = Path(__file__).resolve().parents[1]
ENV_EXAMPLE = REPO_ROOT / ".env.example"

HEADER = """\
# Generated by scripts/write_env_example.py. Do not edit by hand.
# Regenerate with `make env`.
#
# Copy to .env for local development. `make setup` does it for you. Values shown are the
# defaults, except REGISTRY_DATABASE_URL, which is required and shown with the local
# compose DSN.
#
# Settings uses extra="forbid" and reads every key in this file, so ONLY REGISTRY_* keys
# belong here, an unknown or unprefixed key fails at boot rather than being ignored.
# Compose variables such as DB_PORT go in the shell instead.
#
# Secrets never live here. Deployed environments read them from Google Secret Manager.
# .env holds local throwaway values only, and is gitignored.\
"""

#: A field whose name matches one of these never has its default written to a committed
#: file. A secret with a default is already a mistake; writing it into `.env.example` and
#: committing it turns that mistake into a disclosure.
SECRET_HINTS = ("secret", "password", "token", "key", "credential")

SECRET_PLACEHOLDER = "change-me"

#: A required field has no default, but `.env.example` is copied straight to `.env` by
#: `make setup`, so it still needs a value that works locally. Required in code so a
#: deployment cannot silently fall back to a development DSN; helpful in the example.
LOCAL_EXAMPLES = {
    "database_url": "postgresql+asyncpg://registry:registry@localhost:5432/registry",
}


def render_value(name: str, field: FieldInfo) -> str:
    if any(hint in name.lower() for hint in SECRET_HINTS):
        return SECRET_PLACEHOLDER
    if field.is_required():
        return LOCAL_EXAMPLES.get(name, "")
    default = field.default
    if default is None:
        return ""
    if isinstance(default, bool):
        return str(default).lower()
    return str(default)


def render_env_example() -> str:
    prefix = Settings.model_config["env_prefix"]
    lines = [HEADER]
    for name, field in Settings.model_fields.items():
        if field.description:
            lines.append(f"\n# {field.description}")
        lines.append(f"{prefix}{name.upper()}={render_value(name, field)}")
    return "\n".join(lines) + "\n"


def main() -> int:
    content = render_env_example()
    if ENV_EXAMPLE.exists() and ENV_EXAMPLE.read_text(encoding="utf-8") == content:
        print(f"ok   {ENV_EXAMPLE.name} is up to date")
        return 0
    ENV_EXAMPLE.write_text(content, encoding="utf-8")
    print(f"wrote {ENV_EXAMPLE.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
